/*
 *                             The MIT License
 *
 * Wavefront Alignment Algorithms
 * Copyright (c) 2017 by Santiago Marco-Sola  <santiagomsola@gmail.com>
 *
 * This file is part of Wavefront Alignment Algorithms.
 */

#include <stdbool.h>
#include <stdio.h>
#include <string.h>

#include "wavefront/wavefront_align.h"

static const char* const zdrop_pattern =
    "TGCAGAATACTTCCATGAAGGACGTTTCACATTCTCCACCGACTCGTAGAGCATTTTTAACCTCGTGTAACGATGGCGGAGCCTACGACTAGATTTTGTAGATTACGGTCGGGACGCAGTAGCCGCAGTATGAGGCTATTCCGTGAGTCCGCAATTGACCAAACTGGGGCGATCTGCGCGTAAACTTTTCCAGCCCATATCGTCTTTCCCTCGTCTTCTTGCTATCGTCGGGACAACACGCCAACGACTTACCAGACATGGGCTACACGGTTAATCGAGCTTGAACCCGAACTCCTTCACATCATCGCCATCAGGATTGGAGTTTAGTGGAGGGGGTAACCTGGCAGCAATATGTGGGGCATTGCGCCTCGCAATCCGGCTCGGAGCTATACGATTGAAGGGAGTTTCGGTCACTATCTAATCTTCGGGTCAGCGGCGTTCGCCACGAGGAGGGCCTAAGACGTTCCAAATGTAATCGTTAAGGGAAGCCACTTAGACGCGGTGGTGAGGATGTGCTTTACTGAGGTTAGCTAACTAATTGTTATCCGCCTGCCTTAGTCAACCCTAGTTCCTACGGTCAACGGTGCTCCCGGGTTGTGCTAGTCAGTAAACCTTACCAGTGACAACGATATTTTCTGCAGCCTACACGAACGCTTCAGGAGGAGCCCAGGGTAGACGGATGGGACGGGAAGTGTCAATATCTTCCTTACTAACGCTATCCAAAGAGTCCAATTACCTACCAGGGATCATTGTAGGAAGCGGCGGGTTGACTATGTAGCCCATCCGACTGGGCAATGATAACACCTACCCTTGGCTACCAATGCAGATGAAGCCAGACAGTTGCCTCGCGGCGATTGTGCAGACTAAACAGATAGAATTGGCTAGGTCGGGTCGAATACCATCAAAAAAATGCGTACTCACTTGGATGCATGACGACTCGTAACTACCTTCCGCACGATTAGCAATCCTGTGTAAGCCTCACGTTTCCTCAAAGAACGGC";
static const char* const zdrop_text =
    "TGCAGTAATCACTTCCATGTAGGACTGTTCACATGCTCCACGAACTCGTAGATCATTTTAACCCGGTGTAACGTGGCGTAGGCCTACGACTTGATTGTAGATTACGGTACGGGACGCGTAGCCGAGTATGGAAGGCTATTCCGTGAGTCCCAAATCTGACCAAACTGGGGCGATCTGCCGCGTAATCTTCTCAAGCCTTTACGCTTTCCCTCGTTCCTGCTTACCGTCGGGACAAACACGCCAACGGACTTAACCAGACATGGGCTCAGTTACATCGACTTGAACCCGAACTCTTTCACACATAGCCCATCAGGTTGTGGAGTTAGTGACGGGGGTAACCTGGCACAATATGTCGGGATTCGCCTCGAATCCGGCTCGGAGTATACGATCTTAAGGGAGTCTCGGTCATCTCACTTCGGGTCAGCGAGCGTTCGCCATCGAGGAGGCCTAAAACGTCCAAGTTGTAATCGTTGAGGGAAGCCCATTAAACCGGTGGTAGGAAGTGCTTTACTGAGTTAGCAACTAATTGTTATCCGCCTGGGCCTTAGTCAACTCTAGTTCCTACGGTCCAGTGCTCCCGGGTGGCCAGTCCGTAAACCGGTTACAGTGAAACGATATTTTCTGCAGCCTACACGTCACGCGTCAGAATGGCCCAGGTAGACGGATGGGACGTAGGATGTTAATATCTTCTTACTAACGGTGACCAAAAGTCCAATTACGGAACCAGTGGATCATTGTAGGAAGCGGGGTTGAGTATGTAGCTCCCGAGCTGGGCATATAACACCTACCTTGGCTACCAATGCAGATCAAGCCCGCCAGTTGCCGTCGCGCATCCTAAAGACTGAAAAGATAGAGTTGGGCTAGGTCGTGCGGTATACCAATCAAAAAAATTGCGTACCTCCACTTGGATGCATGACGAACTCATAACCACCTCGCACGATTAGCAATCCAGTGTCAAGCCTAACGTTTCCTCGAAGAGACGGC";

static int check_zdrop_piggyback(
    const wavefront_memory_t memory_mode) {
  wavefront_aligner_attr_t attributes = wavefront_aligner_attr_default;
  attributes.distance_metric = gap_affine;
  attributes.memory_mode = memory_mode;
  attributes.alignment_scope = compute_alignment;
  attributes.heuristic.strategy = wf_heuristic_none;
  attributes.system.check_alignment_correct = true;

  wavefront_aligner_t* const wf_aligner = wavefront_aligner_new(&attributes);
  wavefront_aligner_set_heuristic_zdrop(wf_aligner,10,1);
  const int status = wavefront_align(
      wf_aligner,
      zdrop_pattern,(int)strlen(zdrop_pattern),
      zdrop_text,(int)strlen(zdrop_text));

  int failed = 0;
  if (status != WF_STATUS_ALG_COMPLETED && status != WF_STATUS_ALG_PARTIAL) {
    fprintf(stderr,"Z-drop piggyback status mismatch for memory mode %d: %d\n",
        memory_mode,status);
    failed = 1;
  }
  if (cigar_is_null(wf_aligner->cigar)) {
    fprintf(stderr,"Z-drop piggyback produced a null CIGAR for memory mode %d\n",
        memory_mode);
    failed = 1;
  }
  wavefront_aligner_delete(wf_aligner);
  return failed;
}

int main(void) {
  int failed = 0;
  failed |= check_zdrop_piggyback(wavefront_memory_med);
  failed |= check_zdrop_piggyback(wavefront_memory_low);
  return failed;
}
